# Generated by Django 4.2.7 on 2024-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SONG_NAME', models.CharField(max_length=100)),
                ('SONG_PATH', models.CharField(max_length=100)),
                ('PLAYS', models.IntegerField(default=0)),
            ],
        ),
    ]
