# Generated by Django 4.2.7 on 2023-12-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
