# Generated by Django 4.2.7 on 2023-12-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_producto_categorias_producto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='activado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
